### ISSUE TITLE
Getting error : Cannot set property 'internationalPhoneNumber' of undefined

### ISSUE THREAD

**Issue by LearnGrowAndShare** [mareczek/international-phone-number#98]
I have just set up my view like :  
<input type="text" class="form-control" placeholder="921213243" data-ng-model="registration.mobile" international-phone-number required>

And then I am getting below error in console.

angular.js:9778 TypeError: Cannot set property 'internationalPhoneNumber' of undefined
    at link (https://rawgit.com/mareczek/international-phone-number/master/releases/international-phone-number.js:96:53)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js:62:483
    at J (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js:53:345)
    at f (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js:46:399)
    at J (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js:53:286)
    at f (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js:46:399)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js:46:67
    at link (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular-route.min.js:7:388)
    at J (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js:53:345)
    at f (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js:46:399) <input type="text" class="form-control ng-isolate-scope ng-pristine ng-valid" placeholder="example@test.com" data-ng-model="registration.mobile" international-phone-number="" required="">

**Comment by mdurrant** [comment]
I ran into this too on an older project. It turns out this is not compatible with your angular version. I upgraded to the latest stable version and the lib works fine now.

For the record the bower component has > 1.3.0 listed as the dependency, so that's likely the minimum compatible version.

**Comment by LearnGrowAndShare** [comment]
Thanks seems to be working for me also ...
